duckdns:
  container_name: duckdns
  build: https://github.com/ukkopahis/docker-duckdns.git
  network_mode: host
  restart: unless-stopped
  environment:
    PUID: 1000
    PGID: 1000
    # Required variables, define here on in docker-compose.override.yml
    # token from duckdns.org
    TOKEN: ${DUCKDNS_TOKEN:?eg echo DUCKDNS_TOKEN=token >>~/IOTstack/.env}
    # your domain added to duckdns.org (without .duckdns.org)
    SUBDOMAINS: ${DUCKDNS_SUBDOMAINS:?eg echo DUCKDNS_SUBDOMAINS=subdomains >>~/IOTstack/.env}
    # optional your private domain added to duckdns.org (without .duckdns.org)
    # PRIVATE_SUBDOMAINS: ${DUCKDNS_PRIVATE_SUBDOMAINS:-}

