mariadb:
  build: ./.templates/mariadb/.
  container_name: mariadb
  environment:
    - TZ=${TZ:-Etc/UTC}
    - PUID=1000
    - PGID=1000
    - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:?eg echo MARIADB_ROOT_PASSWORD=%randomAdminPassword% >>~/IOTstack/.env}
    - MYSQL_DATABASE=${MARIADB_DATABASE:-default}
    - MYSQL_USER=${MARIADB_USER:-mariadbuser}
    - MYSQL_PASSWORD=${MARIADB_USER_PASSWORD:?eg echo MARIADB_USER_PASSWORD=%randomPassword% >>~/IOTstack/.env}
  volumes:
    - ./volumes/mariadb/config:/config
    - ./volumes/mariadb/db_backup:/backup
  ports:
    - "3306:3306"
  restart: unless-stopped
