  postgres:
    container_name: postgres
    image: postgres:18
    x-comment: Please READ the Postgres document in the IOTstack Wiki BEFORE changing the "18"
    restart: unless-stopped
    env_file:
      - ./services/postgres/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql
      - ./volumes/postgres/db_backup:/backup
