openhab:
  container_name: openhab
  image: "openhab/openhab:latest"
  restart: unless-stopped
  network_mode: host
  volumes:
    - "./volumes/openhab/addons:/openhab/addons"
    - "./volumes/openhab/conf:/openhab/conf"
    - "./volumes/openhab/userdata:/openhab/userdata"
  environment:
    - TZ: ${TZ:-Etc/UTC}
    - OPENHAB_HTTP_PORT: 4050
    - OPENHAB_HTTPS_PORT: 4051
    - EXTRA_JAVA_OPTS: -Duser.timezone=${TZ:-Etc/UTC}
  x-logging:
    options:
      max-size: "5m"
      max-file: "3"

